# ==============================================================================
# Cloud Build - MyAgentsFrontend Main Branch Build
# ==============================================================================
# Comprehensive build for main branch commits
# Runs: Lint + All tests + Web build
# Trigger: Push to main branch
# Machine: E2_HIGHCPU_8 for faster builds
# ==============================================================================

steps:
  # ==============================================================================
  # 1. Build Docker Image
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Building Flutter test image ==="
        docker pull gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest || true

        # Build with commit SHA tag for traceability
        if [ -n "$COMMIT_SHA" ]; then
          docker build \
            -t gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest \
            -t gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA \
            --cache-from gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest \
            -f Dockerfile.test \
            .
        else
          docker build \
            -t gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest \
            --cache-from gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest \
            -f Dockerfile.test \
            .
        fi
    id: 'build-image'

  # ==============================================================================
  # 2. Push Docker Image
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest']
    id: 'push-image'
    waitFor: ['build-image']

  # ==============================================================================
  # 3. Lint (flutter analyze - fail fast gate)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Running Flutter Analyze ==="
        docker run --rm gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest \
          flutter analyze --no-fatal-infos --no-fatal-warnings
    id: 'lint'
    waitFor: ['build-image']

  # ==============================================================================
  # 4. Unit Tests
  # ==============================================================================
  # NOTE: Coverage collection disabled due to VM segfault issues in Cloud Build
  # See: https://github.com/flutter/flutter/issues/issues with coverage + Docker
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Running Flutter Tests ==="
        docker run --rm gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest \
          flutter test --reporter expanded
    id: 'unit-tests'
    waitFor: ['lint']

  # ==============================================================================
  # 5. Build Web Application
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Building Flutter Web Application ==="
        mkdir -p /workspace/web_build

        # Run container to build web
        CONTAINER_ID=$(docker run -d gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest sleep infinity)

        # Build web with release mode
        docker exec $${CONTAINER_ID} flutter build web --release

        # Copy build output
        echo "=== Extracting web build ==="
        docker cp $${CONTAINER_ID}:/app/build/web /workspace/web_build/ || true

        # Cleanup
        docker stop $${CONTAINER_ID} > /dev/null
        docker rm $${CONTAINER_ID} > /dev/null

        # Verify build
        echo "=== Web build contents ==="
        ls -la /workspace/web_build/web/ || echo "Web build may have failed"
    id: 'build-web'
    waitFor: ['unit-tests']

substitutions:
  _IMAGE_NAME: 'myagentsfrontend-test'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
